### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Animationking11** [GamerDuck123/LifeStealSMP#34]
Logs: https://mcpaste.io/051e310119964d5f

**Comment by Animationking11** [comment]
Used newest version

**Comment by GamerDuck123** [comment]
would you mind sending your config.yml?

**Comment by Animationking11** [comment]
https://mega.nz/file/MFBxBYqB#EVfYtIYc8hyhEThSgwYhC540GCW5R4W6rcwZI-kUCgk

**Comment by GamerDuck123** [comment]
So in your config, the first thing you want to do is remove the DIAMOND part in your recipe, that's going to throw another error about not being actually used in the recipe
```
DIAMOND:
  Symbol: "*"
   CustomModelData: 1
   DisplayName: "Heart Shard"
   Lore:
   - "Right click this item to get a heart"
```

Once you've removed that all of your item names need to be uppercase i.e netherite_scrape needs to be -> NETHERITE_SCRAP
This was a limitation in the code, I am currently posting an update (version 0.1.4-PATCH-2) to fix this, but it can also be fixed by doing what I stated above!
